# Generated by Django 4.2.5 on 2023-09-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPortfolioTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_activo', models.CharField(max_length=10)),
                ('act_ticker', models.CharField(max_length=4)),
                ('act_nombre', models.CharField(max_length=50)),
                ('act_pais', models.CharField(max_length=20)),
                ('act_industria', models.CharField(max_length=20)),
            ],
        ),
    ]
