# Generated by Django 4.2.5 on 2023-09-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPortfolioTracker', '0002_activos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_activo', models.CharField(max_length=10)),
                ('lib_ticker', models.CharField(max_length=4)),
            ],
        ),
    ]
