# Generated by Django 4.2.5 on 2023-09-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPortfolioTracker', '0003_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos',
            name='act_mercado',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='activos',
            name='act_moneda',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
