# Generated by Django 4.2.5 on 2023-09-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPortfolioTracker', '0007_rename_act_nombre_activos_act_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='lib_ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPortfolioTracker.activos'),
        ),
    ]
